config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root controller: :chats, action: :index

  resources :chat_messages
  resources :chats

  get 'about', to: 'chats#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
	has_many :chat_messages, dependent: :destroy,
							inverse_of: :chat
			  :user
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user
  belongs_to :chat, inverse_of: :chat_messages

  def as_json(options)
  	super(options).merge(user_avatar_url: user.gravatar_url)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :chat_messages,
  			   dependent: :destroy
           :chats

def gravatar_url
  gravatar_id = Digest::MD5::hexdigest(email).downcase
  "https://gravatar.com/avatar/#{gravatar_id}.png"
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
	end


end

app/controllers/chat_messages_controller.rb
class ChatMessagesController < ApplicationController
	before_action :load_entities

	def create
		@chat_message = ChatMessage.create user: current_user,
										   chat: @chat,
										   message: params.dig(:chat_message, :message)
	
		ChatChannel.broadcast_to @chat, @chat_message 
	end


	protected

	def load_entities
    	@chat = Chat.find params.dig(:chat_message, :chat_id)
 	end

end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create, :edit, :update]
	before_action :load_entities


	def index
		@chats = Chat.all
	end

	def new
		@chat = Chat.new
	end

	def create
    	@chat = Chat.new permitted_parameters

    if @chat.save
      flash[:success] = "Chat room #{@chat.name} was created successfully"
      redirect_to chats_path
    else
      render :new
    end
  end

	def show
		@chat_message = ChatMessage.new chat: @chat
		@chat_messages = @chat.chat_messages.includes(:user)
	
	end

	def edit
		@chat = Chat.find(params[:id])

	end


	def update
		@chat = Chat.find(params[:id])

		@chat.update_attributes(permitted_parameters)
		redirect_to root_path
	end

	def destroy
		@chat = Chat.find(params[:id])
		@chat.destroy
		redirect_to root_path
	end

	def about

	end

	private


	def load_entities
		@chats = Chat.all
		@chat = Chat.find(params[:id]) if params[:id]
	end

	def permitted_parameters
   		params.require(:chat).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper



end

app/helpers/chat_messages_helper.rb
module ChatMessagesHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_chats.html.erb
<br/>
<div class="booyah-box offset-1">
<div class="row">
  <div class="col-12 col-md-3">
    <div class="mb-3">
	
	<%= link_to new_chat_path, class: 'btn btn-primary button' do %>
		Create a room
	<% end %>
	</div>


<% if @chats.present? %>
<nav class="nav flex-column">
	<% @chats.each do |chat| %>
	<%= link_to chat.name, chat_path(chat), class: 'nav-link room-nav-link' %>
 <% end %>
</nav>
<% else %>

<br/>
<div class="text-muted">
	There are no rooms :(
</div>
<%end%>
</div>
</div>
</div>

app/views/chats/_form.html.erb
<%= simple_form_for @chat do |form| %>
<%= form.input :name %>
<%= form.submit "Save", class: 'btn btn-success save' %>
<%end%>

app/views/chats/about.html.erb
  <br />
<div class="col-10 offset-1">
	<h1>About Us</h1>
  <br />
	<p class="text">
    Mychat application was built by <a target="_blank" href="https://github.com/JennyOh1004">Jenny Seulki Oh</a>.
  </p>
	<p class="text">
	Realtime chats are the most common Chat web application.	
	</p>
</div>

app/views/chats/edit.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Edit Your Chat</h1>
  <%= simple_form_for @chat do |f| %>
    <%= f.input :name %>

    <br />
    <%= f.submit 'Update', class: 'btn btn-primary room-send' %>
  <% end %>
</div>

app/views/chats/index.html.erb
<div class="row">
  <div class="col-4">
    <%= render partial: 'chats' %>
</div>

<div class="vl"></div>

<div class="row">
  <div class="booyah-box col-10 offset-1 main">
    <div class="alert alert-primary">
      <h4 class="alert-heading maintext">
        Welcome to the MyChat App!
      </h4>

      <p class="maintext">
        We need to talk.
      </p>


      <p class="text">
        You can create or join a chat from the sidebar.
      </p>
    </div>
</div>
</div>
</div>

app/views/chats/new.html.erb
<br />
<div class="row">
<div class="booyah-box col-10 offset-1">
<h1>
	Creating a room
</h1>

<br />
<%= render partial: 'form' %>

</div>
</div>

app/views/chats/show.html.erb
<h1 class="chat_name">
  <%= @chat.name %>
</h1>

<div class="row">
  <div class="col-12 col-md-3">

<%= link_to 'Edit', edit_chat_path(@chat), class: 'btn btn-primary button2' %>
<%= link_to 'Destroy', chat_path(@chat), method: :delete, data: {confirm: 'Are you sure you want to delete this?'},class: 'btn btn-danger button2' %>
</div>
</div>

<div class="row">
  <div class="col-12 col-md-3">
    <%= render partial: 'chats' %>
  </div>


  <div class="col">
    <div class="room" data-channel-subscribe="chat" data-chat-id="<%= @chat.id %>">
      <% @chat_messages.each do |chat_message| %>
      <div class="room-message-container">
        <div class="row no-gutters">
          <div class="col-auto text-center">
            <img src="<%= chat_message.user.gravatar_url %>" class="avatar" alt="avatar">
          </div>

          <div class="col">
            <div class="message-content">
              <p class="mb-1">
                <%= chat_message.message %>
              </p>

              <div class="text-right">
                <small>
                  <%= chat_message.created_at %>
                </small>
              </div>
            </div>
           </div>
          </div>
        </div>      
      <% end %>
    </div>

    <%= simple_form_for @chat_message, remote: true do |form| %>
      <div class="input-group mb-3">
        <%= form.input :message, as: :string,
                                 wrapper: false,
                                 label: false,
                                 input_html: {
                                   class: 'room-input'
                                 } %>
        <div class="input-group-append">
          <%= form.submit "Send", class: 'btn btn-dark room-send' %>
        </div>
      </div>

      <%= form.input :chat_id, as: :hidden %>
    <% end %>
  </div>
</div>



<div class="d-none" data-role="message-template">
 <div class="chat-message-container">
  <div class="row no-gutters">
    <div class="col-auto text-center">
      <img src="" class="avatar" alt="avatar" data-role="user-avatar">
    </div>

    <div class="col">
      <div class="message-content">
        <p class="mb-1" data-role="message-text"></p>

        <div class="text-right">
          <small data-role="message-date"></small>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RealChat</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-12">
         

     <nav class="navbar navbar-toggleable-md navbar-custom">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'MyChat', root_path, class: 'navbar-brand' %>


      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: 'nav-link nav' %>
          </li>
          <li class="nav-item">
            <%= link_to 'About', about_path, class: 'nav-link nav' %>
          </li>
        </ul>
        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <img class="avatar_sign" src="<%= current_user.gravatar_url %>">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
           </li>
           <% else %>
           <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %>
           </li>
           <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %>
           </li>
           <% end %>

         </ul>
      </div>
    </nav>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

<div class="my-3">
    <%= yield %>
    </div>
    </div>
    </div>
  </div>
  </body>
</html>